table(data$pgender,exclude=NULL)
table(data$ptage2,exclude=NULL)
table(data$race,exclude=NULL)
table(data$ptethnicity,exclude=NULL)
table(data$pt_education_level,exclude=NULL)
table(data$workers_comp,exclude=NULL)
table(data$liability_claim1,exclude=NULL)
table(data$any_major_surgery_in_the_p,exclude=NULL)
table(data$diabetes,exclude=NULL)
table(data$cad,exclude=NULL)
table(data$osteoporosis,exclude=NULL)
table(data$anxiety,exclude=NULL)
table(data$depression,exclude=NULL)
table(data$bmi,exclude=NULL)
table(data$diagnosis,exclude=NULL)
table(data$dominant_symptom1,exclude=NULL)
table(data$motor_def2,exclude=NULL)
table(data$symptom_duration2,exclude=NULL)
table(data$asa_grade,exclude=NULL)
table(data$arthrodesis_performed ,exclude=NULL)
table(data$surgical_approach,exclude=NULL)
table(data$work,exclude=NULL)
table(data$smoker,exclude=NULL)
table(data$odiscore,exclude=NULL)
table(data$eq5dscore,exclude=NULL)
table(data$back_pain_vas,exclude=NULL)
table(data$leg_pain_vas1,exclude=NULL)



table(ds$estimated_blood_loss_cc3,exclude=NULL)
table(ds$ptage2,exclude=NULL)
table(ds$race,exclude=NULL)
table(ds$ptethnicity,exclude=NULL)
table(ds$pt_education_level,exclude=NULL)
table(ds$workers_comp,exclude=NULL)
table(ds$liability_claim1,exclude=NULL)
table(ds$any_major_surgery_in_the_p,exclude=NULL)
table(ds$diabetes,exclude=NULL)
table(ds$cad,exclude=NULL)
table(ds$osteoporosis,exclude=NULL)
table(ds$anxiety,exclude=NULL)
table(ds$depression,exclude=NULL)
table(ds$bmi,exclude=NULL)
table(ds$diagnosis,exclude=NULL)
table(ds$dominant_symptom1,exclude=NULL)
table(ds$motor_def2,exclude=NULL)
table(ds$symptom_duration2,exclude=NULL)
table(ds$asa_grade,exclude=NULL)
table(ds$arthrodesis_performed ,exclude=NULL)
table(ds$surgical_approach,exclude=NULL)
table(ds$work,exclude=NULL)
table(ds$smoker,exclude=NULL)
table(ds$odiscore,exclude=NULL)
table(ds$eq5dscore,exclude=NULL)
table(ds$back_pain_vas,exclude=NULL)
table(ds$leg_pain_vas1,exclude=NULL)


ds <- subset(ds, select=c(pgender, ptage2, race, ptethnicity,pt_education_level, workers_comp, liability_claim1, any_major_surgery_in_the_p, diabetes, cad, osteoporosis, anxiety, depression, bmi, diagnosis, dominant_symptom1, motor_def2, symptom_duration2, asa_grade, arthrodesis_performed, surgical_approach, work, smoker, odiscore, eq5dscore, back_pain_vas, leg_pain_vas1, odiscore.3m, odiscore.12m, eq5dscore.3m, eq5dscore.12m, back_pain_vas.3m, back_pain_vas.12m, leg_pain_vas1.3m, leg_pain_vas1.12m, pt_satisfaction_index.3m, pt_satisfaction_index.12m, los3, estimated_blood_loss_cc3))

res <-rcorr(as.matrix(ds))
M<-res$r
